name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16.17.0  
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: Install node_modules
        run: npm i

      - name: List files
        run: ls -la

      - name: Build the project
        run: npm run build-only:production

      - name: List files
        run: ls -la

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: ${{ secrets.SOURCE }}
          target: ${{ secrets.TARGET }}
