name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 16.17.0  
      - name: Git clone my repo
        uses: actions/checkout@v1

      - name: List files
        run: ls -la

      - name: Send all materials
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "server,public,src,index.html,package-json,vite.config.ts,tailwind.config.js,postcss.config.js"
          target: "/var/www/html/teyes-front"
      
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/html/teyes-front
            npm install
            npm run build-only:production
            cd server/
            pm2 restart TeyesFront.js
